package res

const (
	LogRoutersInit = "Инициализация роутеров"
	LogServerStartedOnHost = "Сервер запустился на хосте: %s:%s"
	LogGetConfigForDB = "Получение конфигурации для БД"
	LogGetDB = "Получение БД"
	LogServerInit = "Инициализация сервера"
	LogServerStart = "Запуск сервера"
	LogAttemptedToConnectToDB = "Попытка подключения к БД: %d\n"
	LogConnectToDB = "Подключение к БД"
	LogEnableToConnectToDBUsingDriver = "Не получилось присоединиться к БД, используя драйвер: %s; Ошибка: %s\n"
	LogDbIsConnected = "База данных %s подключена\n"
	LogFailedToAccessFileEnv = "Не удалось получить доступ к файлу '.env': %v"
	LogValuesFromEnvFileReceived = "Значения из файла '.env' получены."
	LogGettingBodyRequest = "Получение Body запроса"
	LogErrorGettingBody = "Ошибка получения Body: %v"
	LogConvertBodyToUserLogin = "Конвертация Body в модель UserLogin"
	LogErrorConvertingBotyToUserLogin = "Ошибка конвертации Body в UserModel: %v"
	LogPreparationAndValidationOfUserData = "Подготовка и валидация пользовательских данных"
	LogErrorValidationOfUserData = "Ошибка валидации пользовательских данных: %v"
	LogUserAuthorization = "Авторизация пользователя"
	LogErrorUserAuthorization = "Ошибка авторизации пользователя: %v"
	LogConvertDataToJSON = "Конвертация данных в JSON"
	LogErrorConvertDataToJSON = "Ошибка конвертации данных в JSON: %v"
	LogGettingUserFromDB = "Получение пользователя из БД"
	LogErrorGetUser = "Не удалось получить пользователя: %v"
	LogCheckUserPassword = "Проверка пароля пользователя"
	LogUserPasswordDoNotMatch = "Пароли пользователя не совпадают: %v"
	LogGenerateTokenForUser = "Создание токена для пользователя"
	LogErrorCreateToken = "Ошибка создания токена: %v"
	LogCreateTokenInDB = "Создание токена в БД"
	LogErrorCreateTokenInDB = "Ошибка создания токена в БД: %v"
)